In [1]:
# Array{T}
# Array{T, N}

In [1]:
Array{Float64, 3}(undef, (5, 4, 3))

5×4×3 Array{Float64, 3}:
[:, :, 1] =
 2.55599e-314  2.556e-314    2.55674e-314  2.55674e-314
 2.55599e-314  2.556e-314    2.55599e-314  2.55674e-314
 2.55674e-314  2.55674e-314  2.55599e-314  2.55599e-314
 2.55599e-314  2.55674e-314  2.55674e-314  2.55599e-314
 2.556e-314    2.55674e-314  2.55674e-314  2.55684e-314

[:, :, 2] =
 2.55599e-314  0.0  0.0  0.0
 2.55601e-314  0.0  0.0  0.0
 2.55599e-314  0.0  0.0  0.0
 2.55601e-314  0.0  0.0  0.0
 2.55599e-314  0.0  0.0  0.0

[:, :, 3] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  2.55674e-314
 0.0  0.0  0.0  2.55599e-314

In [2]:
Array{Union{Int64,Nothing}, 4}(nothing, (2, 3, 2, 3))

2×3×2×3 Array{Union{Nothing, Int64}, 4}:
[:, :, 1, 1] =
 nothing  nothing  nothing
 nothing  nothing  nothing

[:, :, 2, 1] =
 nothing  nothing  nothing
 nothing  nothing  nothing

[:, :, 1, 2] =
 nothing  nothing  nothing
 nothing  nothing  nothing

[:, :, 2, 2] =
 nothing  nothing  nothing
 nothing  nothing  nothing

[:, :, 1, 3] =
 nothing  nothing  nothing
 nothing  nothing  nothing

[:, :, 2, 3] =
 nothing  nothing  nothing
 nothing  nothing  nothing

In [3]:
Array{Union{String,Missing}}(missing, 4, 3, 2)

4×3×2 Array{Union{Missing, String}, 3}:
[:, :, 1] =
 missing  missing  missing
 missing  missing  missing
 missing  missing  missing
 missing  missing  missing

[:, :, 2] =
 missing  missing  missing
 missing  missing  missing
 missing  missing  missing
 missing  missing  missing

In [5]:
v = Vector(1:60)
arr1 = reshape(v, (5,4,3))

5×4×3 Array{Int64, 3}:
[:, :, 1] =
 1   6  11  16
 2   7  12  17
 3   8  13  18
 4   9  14  19
 5  10  15  20

[:, :, 2] =
 21  26  31  36
 22  27  32  37
 23  28  33  38
 24  29  34  39
 25  30  35  40

[:, :, 3] =
 41  46  51  56
 42  47  52  57
 43  48  53  58
 44  49  54  59
 45  50  55  60

In [6]:
[1 2 3 4; 5 6 7 8]

2×4 Matrix{Int64}:
 1  2  3  4
 5  6  7  8

In [8]:
[1;5;;6;7;;8;9]

2×3 Matrix{Int64}:
 1  6  8
 5  7  9