In [1]:
rvec = [1, 2, 3, 4, 5]

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [2]:
rvec = [1 2 3 4 5 6]

1×6 Matrix{Int64}:
 1  2  3  4  5  6

In [3]:
rvec = [1 2 3; 4 5 6; 7 8 9;]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [4]:
mat2 = [1 2 3
        4 5 6
        7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [5]:
cvec = [1; 2; 3; 4;]

4-element Vector{Int64}:
 1
 2
 3
 4

In [7]:
ndims(cvec)

1

In [8]:
ndims(mat2)

2

In [10]:
size(cvec)

(4,)

In [11]:
size(mat2)

(3, 3)

In [13]:
length(mat2)

9

In [14]:
length(cvec)

4

In [17]:
mat2[2,3]

6

In [18]:
mat2[end, end]

9

In [19]:
mat2[5]

5

In [21]:
cvec1 = [1, 2, 3, 4, 5]
cvec2 = [6, 7, 8, 9, 10]
cvec3 = [11, 12, 13, 14, 15]

5-element Vector{Int64}:
 11
 12
 13
 14
 15

In [22]:
vcat(cvec1,cvec2,cvec3)

15-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15

In [24]:
hcat(cvec1,cvec2,cvec3)

5×3 Matrix{Int64}:
 1   6  11
 2   7  12
 3   8  13
 4   9  14
 5  10  15

In [27]:
cvec1 = [1 2 3 4 5]
cvec2 = [6 7 8 9 10]
cvec3 = [11 12 13 14 15];

In [28]:
vcat(cvec1,cvec2,cvec3)

3×5 Matrix{Int64}:
  1   2   3   4   5
  6   7   8   9  10
 11  12  13  14  15

In [29]:
[cvec1,cvec2,cvec3]

3-element Vector{Matrix{Int64}}:
 [1 2 … 4 5]
 [6 7 … 9 10]
 [11 12 … 14 15]

In [30]:
m1 = [1 2 3;4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [33]:
m2 = [11 12 13; 14 15 16]

2×3 Matrix{Int64}:
 11  12  13
 14  15  16

In [37]:
mver = [m1;m2]

4×3 Matrix{Int64}:
  1   2   3
  4   5   6
 11  12  13
 14  15  16

In [38]:
mhor = [m1 m2]

2×6 Matrix{Int64}:
 1  2  3  11  12  13
 4  5  6  14  15  16

In [39]:
emptymat = Matrix(undef, 2, 3)

2×3 Matrix{Any}:
 #undef  #undef  #undef
 #undef  #undef  #undef

In [41]:
Matrix{Any}(undef,2,3)

2×3 Matrix{Any}:
 #undef  #undef  #undef
 #undef  #undef  #undef

In [42]:
Matrix{Float64}(undef, 3,2)

3×2 Matrix{Float64}:
 2.14953e-314  2.14953e-314
 2.14953e-314  2.14953e-314
 2.14953e-314  2.14953e-314

In [43]:
mat = Matrix{Union{Int64, String}}(undef,2,3)

2×3 Matrix{Union{Int64, String}}:
 #undef  #undef  #undef
 #undef  #undef  #undef

In [44]:
mat[2,3] = 999;
mat[1,2] = "number";

In [45]:
mat

2×3 Matrix{Union{Int64, String}}:
 #undef     "number"  #undef
 #undef  #undef       999

In [46]:
nothing

In [47]:
typeof(nothing)

Nothing

In [48]:
Matrix{Any}(nothing, 3,3)

3×3 Matrix{Any}:
 nothing  nothing  nothing
 nothing  nothing  nothing
 nothing  nothing  nothing

In [50]:
trues(2,3)

2×3 BitMatrix:
 1  1  1
 1  1  1

In [51]:
falses(3,3)

3×3 BitMatrix:
 0  0  0
 0  0  0
 0  0  0

In [52]:
ones(3,4)

3×4 Matrix{Float64}:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

In [55]:
zeros(3,4)

3×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [56]:
rand(5,3)

5×3 Matrix{Float64}:
 0.0701507  0.447842  0.642278
 0.51816    0.631953  0.834124
 0.261062   0.371694  0.177602
 0.1241     0.648961  0.25361
 0.212433   0.525864  0.143266